[project]
name = "byterw"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "wyf7685", email = "69091901+wyf7685@users.noreply.github.com"},
]
dependencies = [
    "pydantic>=2.7.0",
]
requires-python = ">=3.11,<3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "setuptools>=69.5.1",
]
