name: Build

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - C/**
      - tests/**
      - pdm.lock
      - pyproject.toml
      - setup.py

jobs:
  tests:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Install dependencies
        run: pdm install --no-editable --dev

      - name: Execute pytest
        run: pdm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wyf7685/byterw

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        python-version: ["3.11", "3.12"]

    name: "Build: ${{ matrix.os }} / ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}-latest
    needs:
      - tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and build
        run: |
          pip install -U build
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: byterw-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/
